### ISSUE TITLE
Colony mask inference cyto-dl configs use non-portable paths

### ISSUE THREAD

**Issue by pgarrison** [AllenCell/EMT_image_analysis#24]
This issue is about the work-in-progress branch for colony mask inference reproducibility, `sm_colony_mask_pred_test_v0`.

I expect that the colony mask inference will fail outside of AICS because the cyto-dl configs (https://github.com/AllenCellModeling/cyto-dl/pull/441/files) use `/allen/aics` paths. I recommend relative paths (starting with `./`) instead for portability.

**Comment by smishra3** [comment]
Relative paths have been implemented in the current version avoiding the use of absolute path.

**Comment by pgarrison** [comment]
> Relative paths have been implemented in the current version avoiding the use of absolute path.

Great! If you think this is resolved for the colony mask inference in your branch `sm_colony_mask_pred_test_v0`, please close the issue.
